version: "3.1"

volumes:
  postgres: ~

services:
  nginx:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ./docker/hosts/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/hosts/symfony:/etc/nginx/symfony
    ports:
      - "${NGINX_PORT}:80"
    links:
      - php

  postgres:
    ports:
      - "127.0.0.1:6002:5432"
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  php:
    build: docker/images/php
    working_dir: /app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${PWD}:/app
      - ${HOME}/.composer:/.composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    links:
      - postgres
